language: python

sudo: false

cache:
  directories:
    - $HOME/.cache/pip

python:
 - "2.7"

env:
    global:
         - XDG_CACHE_HOME=$HOME/.cache/

install:
  - pip install flake8 pyflakes coverage
  - pip install python-coveralls nose-cov
  - pip install -r requirements.txt

script: # Run test
  - make test

after_success: # Upload coverage to coveralls.io
  - coveralls
